//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adventureWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalterritory
    {
        public int businessEntityId { get; set; }
        public Nullable<int> territoryId { get; set; }
        public Nullable<decimal> salesQuota { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<decimal> commissionPct { get; set; }
    }
}
